### ISSUE TITLE
Removing unsupported kinds from filter makes the relay return everything

### ISSUE THREAD

**Issue by vitorpamplona** [github-tijlxyz/khatru-pyramid#3]
If I send a filter like this: 

```
{
  "kinds":[1010]
}
```

which is an unsupported kind, this line 
https://github.com/github-tijlxyz/khatru-pyramid/blob/de6d6a735e03c7f9f52d72023678867284c5936c/main.go#L82

removes the kind filter and that makes the relay return ALL events. 

The correct way of implementing this would be to get rid of the unsupported kind, BUT not the array itself. The relay should process this:

```
{
  "kinds":[]
}
```

Which should return nothing.

**Comment by github-tijlxyz** [comment]
it seems like this was a khatru issue that is already fixed, we will just need to update dependencies. https://github.com/fiatjaf/khatru/blame/master/policies/filters.go#L65

**Comment by github-tijlxyz** [comment]
if I try to update it i get a khatru panic so maybe @fiatjaf should look at this

**Comment by github-tijlxyz** [comment]
I think this is fixed with https://github.com/github-tijlxyz/khatru-pyramid/commit/7a811c026b965dc32e1c110caa68a6c7c5e85c5e
